#!/bin/sh

set -eu

if [ $# -gt 0 ] && [ "$1" = "prereqs" ]; then
    # No prerequisites.
    exit
fi

if [ ! -x "$DESTDIR/lib/cryptsetup/scripts/multipassdev" ]; then
    exit
fi

. /usr/share/initramfs-tools/hook-functions

copy_file config /etc/cryptsetup-multipassdev/keys
